baseurl = "https://paudelgaurav.github.io/gblog"
title = "Gaurav Writes"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Gaurav Paudel"
    description = "I am a software developer working in wesionaryTeam"
    github = "https://github.com/paudelgaurav"
    email = "paudelgaurav776@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"